warn and die functions

diff --git a/scripts/generate-initramfs b/scripts/generate-initramfs
--- a/scripts/generate-initramfs
+++ b/scripts/generate-initramfs
@@ -8,6 +8,8 @@ Usage: ./generate-initramfs [-mh]
     -m           Update manpages
 EOF
 }
+warn() { printf 'WARNING: %s\n' "$*"; } >&2
+die() { local r=$?; printf 'ERROR: %s\n' "$*"; exit "$r"; } >&2
 sprunge() { curl -F 'sprunge=<-' http://sprunge.us; }
 update_manpage() {
     local cmd=$1 md5 cur_md5
@@ -276,15 +278,12 @@ else
     cp /lib/ld-linux.so.2 initramfs/lib/
 fi || exit
 
-if type tic >/dev/null; then
-    tic -s -o initramfs/lib/terminfo dumb.terminfo
-else
-    printf >&2 'WARNING: not found: tic: %s\n' "Can't create terminfo entry"
-fi
+tic -s -o initramfs/lib/terminfo dumb.terminfo 2>/dev/null ||
+    warn "can't create terminfo entry"
 
 for cmd in "${!commands[@]}"; do
     if ! path=$(type -P "$cmd"); then
-        printf >&2 'WARNING: not found: %s - %s\n' "$cmd" "${commands[$cmd]}"
+        warn "not found: $cmd - ${commands[$cmd]}"
         continue
     fi
     command_paths[$cmd]=$path
